### PR TITLE
Added static files and finish create product

### PR DESCRIPTION
**Pull request by f0rgeAhead**
截屏2024-04-11 下午2 03 12
Made the following changes:

- Added static files
- Finish the create product

### CODE REVIEW

**Review by va1shn9v — APPROVED** [review]

**Comment by tawn33y** [comment]
Looks great @f0rgeAhead, Please add a screenshot of the UI to your main comment. Thanks!

**Comment by va1shn9v** [comment]
Yeah, we need to add tests for this as well right?

**Comment by tawn33y** [comment]
@va1shn9v yes, we may need to - for the CI pipeline. Not sure if the professor's repo has examples of UI testing

**Comment by f0rgeAhead** [comment]
> Looks great @f0rgeAhead, Please add a screenshot of the UI to your main comment. Thanks!

Added

**Comment by jjeangal** [comment]
Great work Wenlong this looks good. Waiting for the tests to approve!

**Comment by jjeangal** [comment]
I see some of the bdd tests are not passing, let us know if you need any help!

**Comment by f0rgeAhead** [comment]
> I see some of the bdd tests are not passing, let us know if you need any help!

Yes, I'm still working on this right now.

**Comment by f0rgeAhead** [comment]
Made the following changes:

- Added test cases
- Modify route of Home page
- Create Product in UI
截屏2024-04-11 下午8 45 33

**Pull request closed without merging**
