### PR TITLE
Add base url response

### LINKED ISSUE #26: Base URL Response
**As a** User
**I need** an API response at the Base URL 
**So that** I can get some useful information about the service
   
 ### Details and Assumptions
 * ```"/"``` is the base URL
 * Should return the information about the service 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a base url
 When I make an API call
 Then it should send back a response with information about the service
```

### PR DESCRIPTION
**Pull request by tawn33y**
This fixes #26

### CODE REVIEW

**Review by va1shn9v — COMMENTED** [review]
@tawn33y 3 tests are failing in this branch, could you check on those, once it is resolved we can go ahead with this PR

**Comment by tawn33y** [comment]
> @tawn33y 3 tests are failing in this branch, could you check on those, once it is resolved we can go ahead with this PR

on it

**Review by jjeangal — APPROVED** [review]

**Comment by tawn33y** [comment]
> > @tawn33y 3 tests are failing in this branch, could you check on those, once it is resolved we can go ahead with this PR
> 
> on it

done!

**Review by jjeangal — APPROVED** [review]
It seems to complete well what we discussed, good job

**Review by va1shn9v — APPROVED** [review]

**Pull request merged**
